image: continuumio/miniconda3

stages:
  - build

build_docs:
  stage: build
  before_script:
    - conda create -y --name python3.10 python=3.10 pip
    - conda init
    - cat /root/.bashrc
    - source /root/.bashrc
    - conda activate python3.10
    - conda install -y conda-forge::pandoc
    - pip install -r requirements.txt
  script:
    - pip3 show madas
    - python3 -m sphinx -T --keep-going -W -b html -d _build/doctrees -D language=en . _build